import { useEffect, useState } from 'react';
import { CloudRain, MapPin, Radio, Sparkles, RefreshCw } from 'lucide-react';

export function WorldIntel() {
  const [intel, setIntel] = useState<any>(null); const [answer, setAnswer] = useState(''); const [loading, setLoading] = useState(true); const [asking, setAsking] = useState(false);
  const auth = { Authorization: `Bearer ${localStorage.getItem('token')}` };
  const load = () => { setLoading(true); fetch('/api/v1/world-intel', { headers: auth }).then(r => r.json()).then(j => setIntel(j.data)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const ask = () => { setAsking(true); fetch('/api/v1/world-intel/ask', { method:'POST', headers:{...auth,'Content-Type':'application/json'}, body:JSON.stringify({prompt:'Using the live weather and public social signals, give a concise resort operations briefing with three prioritized actions and explain the evidence.'}) }).then(r=>r.json()).then(j=>setAnswer(j.data?.text || j.error)).finally(()=>setAsking(false)); };
  const c = intel?.current;
  return <div className="max-w-7xl mx-auto px-4 py-8"><div className="flex justify-between items-start mb-8"><div><p className="text-xs tracking-[.25em] text-cyan-400 font-bold">LIVE OPERATIONS INTELLIGENCE</p><h1 className="text-3xl font-black text-white mt-2">Weather + Social Twin</h1><p className="text-slate-400 mt-1">Every signal below is fetched live and passed to the AI decision layer.</p></div><button onClick={load} className="p-3 rounded-lg bg-slate-800 text-slate-200"><RefreshCw size={18}/></button></div>
  {loading ? <div className="text-slate-400 animate-pulse">Connecting to Open-Meteo and GDELT…</div> : <><div className="grid md:grid-cols-3 gap-4 mb-6"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><CloudRain className="text-cyan-400 mb-4"/><p className="text-slate-400 text-xs uppercase">Live conditions · Open-Meteo</p><div className="text-3xl font-black text-white mt-2">{c?.temperatureC ?? '—'}°C</div><p className="text-sm text-slate-400">{c?.precipitationMm} mm rain · {c?.windKph} km/h wind</p><div className="mt-3 text-xs text-cyan-300">Twin severity: {(c?.severity*100).toFixed(0)}%</div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><Radio className="text-amber-400 mb-4"/><p className="text-slate-400 text-xs uppercase">Public signals · GDELT</p><div className="text-3xl font-black text-white mt-2">{intel?.social?.count}</div><p className="text-sm text-slate-400">weather-related reports found</p></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><Sparkles className="text-violet-400 mb-4"/><p className="text-slate-400 text-xs uppercase">AI context packet</p><p className="text-sm text-slate-200 mt-3">{intel?.aiInput}</p></div></div>
  <div className="grid lg:grid-cols-2 gap-6"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-white mb-4 flex gap-2"><MapPin className="text-rose-400"/>Geospatial impact map</h2><div className="relative h-80 rounded-xl overflow-hidden bg-[#10243a]" style={{backgroundImage:'linear-gradient(rgba(100,180,220,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(100,180,220,.12) 1px,transparent 1px)',backgroundSize:'42px 42px'}}><div className="absolute left-[48%] top-[42%] h-5 w-5 rounded-full bg-cyan-400 ring-8 ring-cyan-400/20"/><div className="absolute left-[62%] top-[32%] h-3 w-3 rounded-full bg-amber-400"/><div className="absolute left-[30%] top-[62%] h-3 w-3 rounded-full bg-rose-400"/><span className="absolute left-[51%] top-[48%] text-xs text-white">Resort · Navi Mumbai</span><span className="absolute right-3 bottom-3 text-[10px] text-slate-400">19.033°N · 73.029°E</span></div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-white mb-4">Real-world reports</h2>{intel?.social?.items?.length ? intel.social.items.map((x:any,i:number)=><a target="_blank" rel="noreferrer" href={x.url} key={i} className="block border-b border-slate-800 py-3 text-sm text-slate-300 hover:text-cyan-300">{x.title}</a>) : <p className="text-slate-500 text-sm">No public reports returned right now; the feed will refresh on demand.</p>}</div></div><div className="mt-6 bg-violet-950/30 border border-violet-500/30 rounded-2xl p-5"><div className="flex justify-between items-center"><h2 className="font-bold text-white">Gemini live briefing</h2><button onClick={ask} disabled={asking} className="bg-violet-600 px-4 py-2 rounded-lg text-sm font-bold">{asking?'Analyzing…':'Ask Gemini'}</button></div>{answer && <pre className="whitespace-pre-wrap text-sm text-violet-100 mt-4 font-sans">{answer}</pre>}</div></>}
  </div>;
}
